config/routes.rb
Pigeons::Application.routes.draw do
  root :to => "club#index"
  resources :clubs
  resources :lofts
  resources :race_stations

  put 'race_stations/:id/distance' => 'race_stations#update_distances'
  put 'lofts/:id/distance' => 'lofts#update_distances'

end

app/models/bird.rb
class Bird < ActiveRecord::Base
  belongs_to :loft
  has_many :race_entries
end

app/models/club.rb
class Club < ActiveRecord::Base
  has_many :lofts
end

app/models/loft.rb
class Loft < ActiveRecord::Base
  belongs_to :club
  has_many :birds
  has_many :race_cards
  has_many :race_distances

  def all_race_distances
    dists = race_distances.inject({}) do |h,d|
      d[:id] = nil
      h[d.race_station.id] = d
      h
    end
    RaceStation.all.each do |station|
      dists[station.id] ||= 
        RaceDistance.new(
          :race_station => station,
          :loft => self,
          :distance_meters => 0)
    end
    dists.sort.map {|x| x[1]}
  end

  #Race distance for a station
  def race_distance_for_station(station_id)
    RaceDistance.
      find_by_race_station_id_and_loft_id(station_id,
                                          self.id)
  end

  # Update race distance (add a new one if not found)
  def update_race_distance(station_id, distance_meters)
    rsd = race_distance_for_station(station_id)
    if rsd
      rsd.distance_meters = distance_meters
    else
      rsd = RaceDistance.new(
        :race_station => RaceStation.find(station_id), 
        :loft => self,
        :distance_meters => distance_meters)
    end
    rsd.save
  end

end

app/models/race.rb
class Race < ActiveRecord::Base
  belongs_to :race_station
  has_many :race_cards
end

app/models/race_card.rb
class RaceCard < ActiveRecord::Base
  belongs_to :loft
  belongs_to :race
  belongs_to :race_distance
  has_many :race_entries
end

app/models/race_distance.rb
class RaceDistance < ActiveRecord::Base
  belongs_to :race_station
  belongs_to :loft
end

app/models/race_entry.rb
class RaceEntry < ActiveRecord::Base
  belongs_to :race_card
  belongs_to :bird
end

app/models/race_station.rb
class RaceStation < ActiveRecord::Base
  has_many :race_distances
  has_many :races

  def all_race_distances
    dists = race_distances.inject({}) do |h,d|
      d[:id] = nil
      h[d.loft.id] = d
      h
    end
    Loft.all.each do |loft|
      dists[loft.id] ||=
        RaceDistance.new(
          :race_station => self,
          :loft => loft,
          :distance_meters => 0)
    end
    dists.sort.map {|x| x[1]}
  end

  #Race distance for a station
  def race_distance_for_loft(loft_id)
    RaceDistance.
      find_by_race_station_id_and_loft_id(self.id,
                                          loft_id)
  end

  # Update race distance (add a new one if not found)
  def update_race_distance(loft_id, distance_meters)
    rsd = race_distance_for_loft(loft_id)
    if rsd
      rsd.distance_meters = distance_meters
    else
      rsd = RaceDistance.new(
        :race_station => self, 
        :loft => Loft.find(loft_id),
        :distance_meters => distance_meters)
    end
    rsd.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def index
    @clubs = Club.all
  end

  def show
    @club = Club.find(params[:id])
    session[:current_club_id] = params[:id]
  end

  def new
    @club = Club.new
  end

  def edit
    @club = Club.find(params[:id])
  end

  def create
    @club = Club.new(params[:club])
    if @club.save
      redirect_to @club, :notice => "Club was successfully created."
    else
      render :action => "new"
    end
  end

  def update
    @club = Club.find(params[:id])
    if (@club.update_attributes(params[:club]))
      redirect_to(@club, :notice => "Club was successfully updated.")
    else
      render :action => "edit"
    end
  end

  def destroy
    @club = Club.find(params[:id])
    @club.destroy
    redirect_to(clubs_url)
  end

end

app/controllers/lofts_controller.rb
class LoftsController < ApplicationController
  def show
    @loft = Loft.find(params[:id])
  end

  def new
    @loft = Loft.new
  end

  def edit
    @loft = Loft.find(params[:id])
  end

  def create
    @loft = Loft.new(params[:loft])
    @loft.club = Club.find(session[:current_club_id])
    if @loft.save
      redirect_to @loft, :notice => "Loft was successfully created."
    else
      render :action => "new"
    end
  end

  def update
    @loft = Loft.find(params[:id])
    if (@loft.update_attributes(params[:loft]))
      redirect_to(@loft, :notice => "Loft was successfully updated.")
    else
      render :action => "edit"
    end
  end

  def destroy
    @loft = Loft.find(params[:id])
    @loft.destroy
    redirect_to(lofts_url)
  end

  def update_distances
     @loft = Loft.find(params[:id])
     distances = params[:loft][:race_distances]
     distances.each do |d|
       @loft.update_race_distance(d[:race_station_id], d[:distance_meters])
     end
     redirect_to @loft, :notice => "Distances successfully updated."
  end

end

app/controllers/race_stations_controller.rb
class RaceStationsController < ApplicationController
  def index
    @race_stations = RaceStation.all
  end

  def show
    @race_station = RaceStation.find(params[:id])
    session[:current_race_station_id] = params[:id]
  end

  def new
    @race_station = RaceStation.new
  end

  def edit
    @race_station = RaceStation.find(params[:id])
  end

  def create
    @race_station = RaceStation.new(params[:race_station])
    if @race_station.save
      redirect_to @race_station, :notice => "Race Station was successfully created."
    else
      render :actin => "new"
    end
  end

  def update
    @race_station = RaceStation.find(params[:id])
    if @race_station.update_attributes(params[:race_station])
      redirect_to(@race_station, :notice => "Race Station was successfully updated.")
    else
      render :action => "edit"
    end
  end

  def destroy
    @race_station = RaceStation.find(params[:id])
    @race_station.destroy
    redirect_to(race_stations_url)
  end

  def update_distances
    @race_station = RaceStation.find(params[:id])
    distances = params[:race_station][:race_distances]
    distances.each do |d|
      @race_station.update_race_distance(d[:loft_id], d[:distance_meters])
    end
    redirect_to @race_station, :notice => "Distances successfully updated."
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/club_helper.rb
module ClubHelper
end

app/helpers/lofts_helper.rb
module LoftsHelper
end

app/helpers/race_stations_helper.rb
module RaceStationsHelper
end

app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing club</h1>

<%= render 'form' %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<h1>Clubs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Contact</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clubs.each do |club| %>
  <tr>
    <td><%= club.name %></td>
    <td><%= club.contact %></td>
    <td><%= link_to 'Show', club %></td>
    <td><%= link_to 'Edit', edit_club_path(club) %></td>
    <td><%= link_to 'Del', club, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New club', new_club_path %>

app/views/clubs/new.html.erb
<h1>New club</h1>

<%= render 'form' %>

<%= link_to 'Back', clubs_path %>

app/views/clubs/show.html.erb
<h1>Club</h1>

<p><strong>Code: </strong><%= @club.code %></p>
<p><strong>Name: </strong><%= @club.name %></p>
<p><strong>Contact: </strong><%= @club.contact %></p>
<p><strong>Notes: </strong><%= @club.notes %></p>

<%= link_to 'Edit', edit_club_path %>
<%= link_to 'Back', clubs_path %>

<h2>Lofts</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Owner</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @club.lofts.each do |loft| %>
  <tr>
    <td><%= loft.name %></td>
    <td><%= loft.owner %></td>
    <td><%= link_to 'Show', loft %></td>
    <td><%= link_to 'Edit', edit_loft_path(loft) %></td>
    <td><%= link_to 'Del', loft, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New loft', new_loft_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pigeons</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" %>
  <%= javascript_include_tag 'rails' %>
  <%= csrf_meta_tag %>
</head>
<body>
    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:error] %>
      <p class="error"><%= flash[:error] %></p>
    <% end %>

<%= yield %>

</body>
</html>

app/views/lofts/_form.html.erb
<%= form_for(@loft) do |f| %>
  <% if @loft.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loft.errors.count, "error") %> prohibited this loft from being saved:</h2>

      <ul>
      <% @loft.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lofts/edit.html.erb
<h1>Editing loft</h1>

<%= render 'form' %>

<%= link_to 'Show', @loft %> |
<%= link_to 'Back', @loft.club %>

app/views/lofts/new.html.erb
<h1>New loft</h1>

<%= render 'form' %>

<%= link_to 'Back', clubs_path %>

app/views/lofts/show.html.erb
<h1>Loft</h1>

<p><strong>Name: </strong><%= @loft.name %></p>
<p><strong>Lat: </strong><%= @loft.lat %></p>
<p><strong>Long: </strong><%= @loft.long %></p>
<p><strong>Contact: </strong><%= @loft.owner %></p>
<p><strong>Notes: </strong><%= @loft.notes %></p>

<%= link_to 'Edit', edit_loft_path %>
<%= link_to 'Back', @loft.club %>

<h2>Distances</h2>

<%= form_for @loft, :url =>
{:action => :update_distances} do |loft_form| %>
  <%= loft_form.hidden_field :id %>
  <table>
    <tr>
      <th>Loc</th>
      <th>Distance</th>
    </tr>

    <% @loft.all_race_distances.each do |race_distance| %>
      <%= loft_form.fields_for 'race_distances[]', race_distance do |distance_fields| %>
        <tr>
          <td>
            <%= link_to(race_distance.race_station.name, 
                        race_station_path(race_distance.race_station.id)) %>
          </td>
          <td>
            <%= distance_fields.text_field :distance_meters %>
            <%= distance_fields.hidden_field :race_station_id %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
  <div class="actions">
    <%= loft_form.submit %>
  </div>
<% end %>

app/views/race_stations/_form.html.erb
<%= form_for(@race_station) do |f| %>
  <% if @race_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race_station.errors.count, "error") %> prohibited this race_station from being saved:</h2>

      <ul>
      <% @race_station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br />
    <%= f.text_field :long %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/race_stations/edit.html.erb
<h1>Editing race stations</h1>

<%= render 'form' %>

<%= link_to 'Show', @race_station %> |
<%= link_to 'Back', race_stations_path %>

app/views/race_stations/index.html.erb
<h1>Race Stations</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @race_stations.each do |race_station| %>
  <tr>
    <td><%= race_station.code %></td>
    <td><%= race_station.name %></td>
    <td><%= link_to 'Show', race_station %></td>
    <td><%= link_to 'Edit', edit_race_station_path(race_station) %></td>
    <td><%= link_to 'Del', race_station, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New race station', new_race_station_path %>

app/views/race_stations/new.html.erb
<h1>New race station</h1>

<%= render 'form' %>

<%= link_to 'Back', race_stations_path %>

app/views/race_stations/show.html.erb
<h1>Race Station</h1>

<p><strong>Code: </strong><%= @race_station.code %></p>
<p><strong>Name: </strong><%= @race_station.name %></p>
<p><strong>Lat: </strong><%= @race_station.lat %></p>
<p><strong>Long: </strong><%= @race_station.long %></p>

<%= link_to 'Edit', edit_race_station_path %>
<%= link_to 'Back', race_stations_path %>

<h2>Distances</h2>

<%= form_for @race_station, :url =>
    {:action => :update_distances} do |race_station_form| %>
  <%= race_station_form.hidden_field :id %>
  <table>
    <tr>
      <th>Loft</th>
      <th>Distance</th>
    </tr>

    <% @race_station.all_race_distances.each do |race_distance| %>
      <%= race_station_form.fields_for 'race_distances[]', race_distance do |distance_fields| %>
        <tr>
          <td>
            <%= distance_fields.hidden_field :loft_id %>
            <%= link_to(race_distance.loft.name, loft_path(race_distance.loft.id)) %>
          </td>
          <td>
            <%= distance_fields.text_field :distance_meters %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
  <div class="actions">
    <%= race_station_form.submit %>
  </div>
<% end %>